- src/handle_action.cpp
对于备份世界功能的实现，暂时不再使用C++ 17的新特性"filesystem"，使用对于C++17"filesystem"的第三方实现
> 使用对于filesystem的第三方实现

- .github/workflows/release.yml
> 触发分支由master修改为main

- .github/workflows/push-translation-template.yml
- .github/workflows/release.yml
> 添加build工作流测试--

- src/monmove.cpp
- src/monstergenerator.cpp
- src/mtype.h
Reverts WhiteCloud0123/CDDA-Breeze#38
> Revert "添加一种flag，可以使得怪物推动载具这个行为本身不再损害载具"

- src/monmove.cpp
- src/monstergenerator.cpp
- src/mtype.h
> 添加一种flag，使得怪物可以在不主动损害到载具的情况下推动载具

- src/version.h
> 修正Windows版本号

- .github/workflows/release.yml
> 设置release.yml

- .github/workflows/release.yml
> 安卓构建，应用jdk11

- .github/workflows/release.yml
Reverts WhiteCloud0123/CDDA-Breeze#57
> Revert "更新tag"

- msvc-full-features/Cataclysm-lib-vcpkg-static.vcxproj
- msvc-full-features/Cataclysm-vcpkg-static.sln
- msvc-full-features/prebuild.cmd
Reverts WhiteCloud0123/CDDA-Breeze#48
> Revert "移除prebuild.md,并在相关解决方案里删除相应事件"

- .github/workflows/release.yml
- android/gradle.properties
- src/action.h
- src/character.cpp
- src/handle_action.cpp
- src/monster.cpp
- src/mtype.h
- src/suffer.cpp
- src/version.h
Reverts WhiteCloud0123/CDDA-Breeze#63
> Revert "添加"丧尸主宰"开局"

- src/game.cpp
> 调整丧尸自然变友好的概率为1/100，对于身为丧尸主宰的玩家而言

- data/mods/Breeze/monster.json
- data/mods/Breeze/profession.json
- data/mods/default.json
> 丧尸主宰职业-part-02

- msvc-full-features/Cataclysm-lib-vcpkg-static.vcxproj
- src/activity_actor.cpp
- src/activity_actor_definitions.h
- src/character.h
- src/crafting.cpp
> 缓存制作速度的工作台乘数  ------来自 SurFlurer

- src/activity_actor.cpp
- src/crafting.cpp
- src/game.cpp
> 清理PR#73中的测试注释

- README.md
> readme标点小修复

- src/monexamine.cpp
> 去除重复的判断 在PR#83

- src/game.cpp
- src/monexamine.cpp
None
1 身为丧尸主宰的玩家对敌对的丧尸怪物可以执行支配指令，如果怪物当前生命值小于最大生命值的百分之10(向下取整)，那么支配成功，否则失败
2 在 #83 中，去除多余的判断
> 丧尸主宰职业第四部分 +  PR 83中去除多余的判断

- src/monexamine.cpp
> 使用const修饰并显式用item& 取代auto  在PR #83

- src/monexamine.cpp
> 将 "Remove bag from" 的位置向后微调   在PR #83

- src/avatar.cpp
- src/character.cpp
- src/character.h
- src/character_attire.cpp
- src/character_inventory.cpp
- src/iexamine.cpp
- src/iuse.cpp
- src/npc.cpp
- src/suffer.cpp
> 缓存角色的辐射水平------来自SurFlurer

- src/overmap_ui.cpp
None
稍微改善一下，如果宠物乱跑以至于玩家不太方便寻找的问题。
> 在ASCII地图上绘制角色视觉范围内的宠物

- data/mods/Breeze/profession.json
- data/mods/Breeze/scenario.json
- src/monmove.cpp
None
1 将丧尸主宰职业绑定为一个场景，点数调整为7
2 注释掉部分调试日志打印信息
> 丧尸主宰职业第五部分+杂项

- src/overmap_ui.cpp
> 阿斯克码地图上，如果宠物与玩家在同一格内，不要绘制宠物图标

- src/character.cpp
> 修复弹出机甲，手中的机甲武器没有正常移除的问题

- src/action.cpp
- src/action.h
- src/avatar.h
- src/game.cpp
- src/handle_action.cpp
- src/monexamine.cpp
- src/savegame_json.cpp
None
添加了一个窗口，用于显示当前职业情况，目前只有身为丧尸主宰的玩家可用。
职业等级可以在未来进行扩展
> 丧尸主宰职业第七部分

- src/game.cpp
> 清理测试信息输出 + 改变部分输出的信息

- src/avatar.h
- src/game.cpp
- src/handle_action.cpp
- src/monexamine.cpp
- src/savegame_json.cpp
> 修复没有成功读取数据的问题

- src/game.cpp
- src/handle_action.cpp
- src/monexamine.cpp
> 修复职业等级升级检测

- src/monexamine.cpp
> 优化了从宠物背包中取出物品的过程

- src/options.cpp
> 自动保存改为false

- src/options.cpp
> 怪物进化时间比率调整为40.00

- src/monexamine.cpp
None
在游戏中，给宠物安装上背包之后，游戏并没有正确的处理背包在安装之前已有的内容。现在进行修复。
> 修复给宠物安装上背包之后，背包之前的物品没有正确处理的问题

- src/monexamine.cpp
> 修复PR #117遗留的问题

- src/monexamine.cpp
> 继续修复 PR #117

- android/app/build.gradle
> 指定安卓版本号-part-03

- android/app/build.gradle
> 指定安卓版本号-part-04

- src/monster.cpp
None
引入怪物等级绝对是向RPG方向最严重的一次滑坡，在目前的游戏的既有的强调真实的大量内容下，实在是冲突感太严重，经过深思熟虑后再引入绝对是更好的。还是将其限定为“只有玩家是丧尸主宰的情况下，并且只有丧尸宠物才能获得经验值”。
丧尸主宰场景中的玩家是一位极其特殊的丧尸主宰，他仍然是人类，但同时又有了可以支配丧尸的能力，与其他丧尸是敌对的关系，未来，会设计一下“丧尸主宰对丧尸主宰”的挑战，在设定上是很有意思的，类似于“你面临的最大威胁是---------另一位丧尸主宰”，但可以肯定，其他的丧尸主宰绝不是最大的威胁。也有可能会设计一下其他的身为人类也有了支配丧尸的能力的npc，这些npc对上主角应该也很有意思。
玩家身边跟着一堆丧尸，想融入末日后的世界绝不简单。未来，在游戏设计上，追随玩家的npc不会攻击玩家的丧尸宠物，而其他的npc，这会是是一个很好的设计。
> PR #136 调整，只有玩家是丧尸主宰的情况下，并且只有丧尸宠物才能获得经验值

- src/monster.cpp
> 补上丧尸物种判定 在PR #137

- data/mods/Breeze/monster.json
- src/monexamine.cpp
- src/monster.h
- src/monstergenerator.cpp
- src/mtype.h
- src/savegame_json.cpp
None
让部分怪物可以装备武器。
丧尸主宰职业:
为开局宠物“丧尸犬-TheFirst" 添加了“可以装备武器”flag
> 部分怪物可以装备武器-第一部分

- src/monexamine.cpp
> 在宠物菜单添加移除武器的选项

- src/monexamine.cpp
> 如果武器对于宠物来说太重，那么不能装备

- src/monster.cpp
> 将武器的钝击伤害作为怪物的近战伤害的加成

- src/monexamine.cpp
None
宠物交互菜单:
1 查看属性更名为查看状态，并在其中添加了两个可查看项目，为武器和防具
2 除丧尸主宰职业外的玩家，查看状态只能查看是否装备武器与防具
> 扩展宠物交互菜单“查看状态”显示的信息

- src/do_turn.cpp
None
采用简单有效的方案。
每天回复的血量由两部分构成:
第一部分，先按regenerates的数值回复血量。
第二部分，在第一部分的基础上，非丧尸物种的怪物每天自然回复百分之5的血量，至少为恢复1点血量。
> 让怪物每天可以自然回复血量

- src/monexamine.cpp
> 宠物交互菜单: 非丧尸主宰职业的情况下，宠物的等级和经验值也可以在“查看状态”中查看

- src/monster.cpp
> 让怪物装备的武器在死亡后掉落

- src/do_turn.cpp
- src/monexamine.cpp
> 宠物交互菜单: 更改生命值的显示样式

- src/monexamine.cpp
> 尝试将物品放入宠物身上的背包的时候，考虑所能容纳的最大长度

- src/character_escape.cpp
- src/monattack.cpp
> 修复 PR #186 遗留的问题

- src/game.cpp
None
执行`can_revive`的过程，包括了`is_corpse`，因此将一个多余的`is_corpse`删除
> 去除多余的判断-在game.cpp

- src/character.cpp
> NPC死亡时，掉落物附着尸体上

- src/character.cpp
This reverts commit a099c9ce1668bae84d492a3c4df1d844bf08ce54.
None
> Revert "NPC死亡时，掉落物附着尸体上"

- src/game.cpp
- src/monexamine.cpp
> 丧尸主宰职业: 补上耐力检查

- src/action.cpp
- src/action.h
- src/handle_action.cpp
> 预留位置以在将来方便的测试一些网络功能

- msvc-full-features/Cataclysm-common.props
> 尝试修复GitHub工作流MSVC构建错误

- src/game.cpp
- src/handle_action.cpp
- src/network.cpp
- src/network.h
> 添加一个简单的网络测试

- src/melee.cpp
> 当远距攻击的时候，如果攻击轨迹有友好的宠物或者npc，添加一个警告

- src/monattack.cpp
> 对于PR #216 ， 使用一个更好的判断

- src/melee.cpp
> 补充缺失的efftype_id

- src/action.cpp
- src/action.h
- src/handle_action.cpp
> 丧尸主宰职业: 融合丧尸尸体——第一部分 + 在develop分支，将网络功能选项暂时移除

- .github/workflows/release.yml
> GitHub工作流步骤名称修改

- .github/workflows/release.yml
> 打包安卓版本的同时加上音乐

- .github/workflows/release.yml
> 调整release.yml的格式

- data/mods/Breeze/monster.json
> 增加放荡吞噬者与融合特遣队的flag: 可以装备武器 + PET_MOUNTABLE

- src/monster.cpp
> 修复怪物升级没有提升速度的问题

- src/monexamine.cpp
> 丧尸主宰职业: 查看状态可以查看 当前速度 和 基础速度

- src/avatar_action.cpp
> 机甲不适用于“骑乘状态下，所骑乘的怪物可以攻击玩家的近战攻击的目标”

- src/monexamine.cpp
> 丧尸主宰职业: 修复查看状态中的基础速度显示错误

- src/monster.cpp
> 将怪物的等级带来的伤害和速度的增益*2

- src/monster.cpp
> 修正怪物击杀NPC时的经验计算

- src/monster.cpp
> 修正怪物升级时的speed_base的计算

- .github/workflows/release.yml
> 在release.yml中，将prerelease的值改为false

- src/do_turn.cpp
> 修复死亡后回到主菜单，之后载入存档出现任务重复的问题 + 去掉不必要的“保存overmap“

- .github/workflows/release.yml
> GitHub工作流: 打包windows版的时候不再包含音乐

- data/mods/Magiclysm/monsters/zombified_monsters.json
> [大魔法]: 让丧尸圣诞猫可以被骑乘

- src/game.cpp
> 丧尸主宰职业: 复活丧尸后，让丧尸的物品掉落在复活后的丧尸的位置

- src/monattack.cpp
> 将 parrot_at_danger 中的近乎决定性的概率判断提前

- gfx/MshockXotto+/tile_config.json
- src/cata_tiles.cpp
- src/cata_tiles.h
- src/options.cpp
> DDA Port: 绘制低级z轴画面——来自  Rewryte

- src/options.cpp
> 默认开启3D视野，3D视野垂直可见范围的默认值设定为1

- src/avatar_action.cpp
> 部分移植-BN端-来自scarf002：更顺畅的上下梯子流程

- src/explosion.cpp
- src/flag.cpp
- src/flag.h
- src/map.cpp
- src/map.h
- src/posix_time.cpp
- src/posix_time.h
> 初步移植-BN端-来自DeltaEpsilon7787：更酷的爆炸规则 0.2阶段

- src/game.cpp
- src/mattack_actors.cpp
> 修复继续扔目标的判定+精英怪物连招

- data/raw/keybindings.json
- src/game.cpp
> 为“退出到游戏开始界面”选项添加快捷键

- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/ISSUE_TEMPLATE/feature_request.yaml
> issue模板翻译 v0.1

- src/character.h
- src/craft_command.cpp
- src/crafting.cpp
> DDA端-来自lispcoc：关于npc制作的后续修复

- data/mods/Breeze/modinfo.json
> 修改 自带的“微风”mod 的描述

- src/game.cpp
- src/savegame_json.cpp
- src/vehicle.cpp
- src/vehicle.h
- src/vehicle_use.cpp
1 首先给直升机安装 “可编程自动驾驶仪器”
2  飞起来之后，选择“交给自动驾驶仪来保持平稳”
3  之后你可以自由的在直升机上活动
4  重新获取控制权，只需要回到驾驶位置按“^”
5 你可以将速度降为0，再移交控制权，也可以留有速度移交控制权，如果载具留有一定速度，会先在空中滑行一段时间。
> 载具悬停-灵感来自BN

- src/monster.cpp
- src/options.cpp
> 添加一个选项来让玩家选择是否动态化怪物的等级

- data/json/effects.json
- src/clzones.cpp
- src/do_turn.cpp
- src/explosion.cpp
- src/game.cpp
- src/npc.cpp
- src/npc.h
- src/npcmove.cpp
- src/npctalk.cpp
- src/options.cpp
None
- 爆炸相关平衡。一颗手雷不再能炸毁墙壁。降低了弹片的波及范围。
- 修复“不正确地生成大量敌对NPC”的问题
- DDA端-来自Night-Pryanik：在“和他人交谈”的菜单上加入一个选项可以命令npc前往指定位置，到达后，npc会再返回。工作方式与DDA一致。
- 派系访问 v0.1 。 再常规选项卡添加一个名为“派系访问”的选项，在开启的情况下，如果“自由商会”对你的好感度不至于太低，那么大概间隔10天半左右的时间，会在你的附近生成所属派系的交易人员，你与他们只能进行交易活动。游戏新添加了一个区域为“交易区域”，你可以先在区域管理上创建一片交易区域，之后生成的交易人员会在指定的交易区域等你交易，他们会等待10分钟，之后会自行离开。如果你没有创建一片交易区域，那么交易人员会以你当前位置为目标。推荐创建一片交易区域。此选项目前默认为关。
> 爆炸相关平衡 + DDA端：命令NPC前往指定地点 + 修复大量生成

- src/do_turn.cpp
None
之前居然看错了循环的结束位置了......真的是。
修复“由低征服度派系派来的刺客有时重复生成”的问题
修复“来自自由商户的交易员有时重复生成”的问题
修复“派系征服度下降”有时重复计算问题
> 修复“新增的派系处理的逻辑误放在了不恰当的循环“而导致的各种问题

- data/raw/keybindings.json
- src/game.cpp
> 移除已经没有实际作用的快捷键绑定

- src/ParticleSystem.cpp
- src/ParticleSystem.h
- src/animation.cpp
- src/options.cpp
- src/sdltiles.cpp
> 为“细雨”、“雨”应用上粒子系统

- src/sdltiles.cpp
> 对PR #326 的后续完善

- data/mods/speedydex/modinfo.json
None
原本的敏捷速度加成mod，敏捷每超过12一点，增加两点速度。
现在进行调整，调整到敏捷超过8即可获取增益。
> 提升“敏捷速度加成”mod获取增益的最低敏捷标准

- src/do_turn.cpp
- src/faction.cpp
None
- 增加交易员生成要求的条件：玩家必须处于营地的范围（三格）
- 在派系界面，显示距离下一次交易员访问的回合数
> 派系访问 v0.15

- src/creature.h
- src/flood_fill.h
- src/lightmap.cpp
- src/map.cpp
- src/map.h
- src/monmove.cpp
> DDA端-来自kevingranade : 通过预先计算怪物的可访问区域来优化怪物的攻击性检查

- src/npcmove.cpp
None
当玩家没有设置交易区域的时候，是直接设定玩家的位置为他们的目标，这显然会不断的在信息栏输出“让我过去”这种类型的话，实际上这些交易员都是短暂存在的，他们完成短短的交易行为后，他们会在离开玩家一段距离后自动的在程序层面设置为“幻觉”，所以没有必要让他们为一个根本不可能最终到底的位置（他们仅仅会在一定时间内仅仅地跟着玩家）说“请让我过去”这样的话。
> 派系访问：交易员行为的优化

- src/npcmove.cpp
> 对 PR #334 的后续补充

- src/faction.cpp
None
- 在派系界面，更加具体的显示玩家在不在营地附近
- 营地附近有敌对的怪物存在，不会通过自由商会的评估，最终也不会有交易人员到达
> 派系访问 v0.16

- src/ParticleSystem.cpp
- src/sdltiles.cpp
> 移除对于particle_system的冗余的判断

- src/faction.cpp
> 派系界面：将“你当前不处于营地的范围”的字体颜色变淡

- .github/workflows/release.yml
> 更改msvc发布版的名称

- data/json/bionics.json
- data/json/items/bionics.json
- data/json/npcs/exodii/exodii_merchant_itemlist.json
- data/json/proficiencies/misc.json
- src/bionics.cpp
> 添加两个新的CBM到鲁比克的商品里，分别可以获得直升机驾驶和飞行器机械师这两个专长

- data/json/overmap/overmap_special/specials.json
> 提高难民中心的生成优先级

- src/active_item_cache.cpp
- src/active_item_cache.h
- src/character.cpp
- src/handle_liquid.cpp
- src/inventory.cpp
- src/inventory.h
- src/item.cpp
- src/item.h
- src/item_location.cpp
- src/map.cpp
- src/map.h
- src/savegame_json.cpp
- src/submap.cpp
- src/vehicle.cpp
- src/vehicle_part.cpp
- src/visitable.cpp
>  有关活动项目的优化

- src/melee.cpp
> DDA端-来自Surflurer：为赤手空拳的npc缓存武器值，以加快npc::regen_ai_cache()

- src/cata_lazy.h
- src/character.cpp
- src/character.h
- src/creature.cpp
- src/creature.h
None
难民中心NPC场景测试
之前
之后
极大的降低了这一部分检查带来的性能损耗
> DDA端-来自akrieger：缓存npc的死亡状态

- src/ParticleSystem.cpp
- src/sdltiles.cpp
> 校准立绘和特效显示的位置

- src/game_inventory.cpp
- src/inventory_ui.cpp
- src/inventory_ui.h
- src/item.cpp
- src/item.h
- src/item_location.cpp
> DDA端-来自andrei8l：item collation

- src/inventory_ui.cpp
> 跟进 PR #363

- src/npctalk.cpp
> DDA端-来自Surflurer：可能的情况下，使用当前地图做地形变换，而不是总是去加载一张地图

- src/ParticleSystem.cpp
- src/npctalk.cpp
- src/sdltiles.cpp
- src/sdltiles.h
> Android端校准立绘和特效的显示位置

- src/options.cpp
- src/sdltiles.cpp
> 添加可以关闭立绘的选项

- src/inventory_ui.cpp
- src/inventory_ui.h
- src/uistate.h
> 记录显示所有内容物后的界面状态

- src/options.cpp
- src/sdltiles.cpp
> 更改立绘开关设置名称

- data/raw/keybindings.json
- src/bionics.cpp
- src/bionics.h
- src/bionics_ui.cpp
- src/character.cpp
> DDA端-来自Rewryte：可以隐藏cbm在玩家身上的的外观

- src/action.cpp
- src/vehicle.cpp
> DDA端-来自Surflurer：杂项优化

- src/vehicle_use.cpp
> 更改打开运输器的选项的名称

- src/do_turn.cpp
> 改善访客的刷新与消失

- src/do_turn.cpp
> 整理生成访客和敌对npc的代码

- src/do_turn.cpp
- src/map.cpp
- src/map.h
None
将与运输器有关的检查和处理移动到更加合适的地方，降低性能开销。
- 将与运输器主要的检查与处理的逻辑从`map::process_conveyor_belt`移动到`map::process_items_in_vehicles`。
- 将`map::process_conveyor_belt`更名为`map::process_others`，预备用途。
> 将与运输器有关的检查和处理移动到更加合适的地方，降低性能开销

- src/map.cpp
> 优化有关运输器的检查

- src/activity_item_handling.cpp
- src/pickup.cpp
> 修复自动增加收藏物品备注的过程中大地图格坐标的计算

- data/json/monsters/zed-classic.json
- data/json/monsters/zed_misc.json
- data/json/monsters/zed_soldiers.json
- src/cata_tiles.cpp
- src/monattack.cpp
- src/monattack.h
- src/monstergenerator.cpp
None
丧尸浩克、狂暴丧尸兽、飞行员丧尸、军装丧尸、士兵丧尸可以自主的装备上武器。他们没有太高的智力，他们就只是靠着生前身体留下的记忆和本能去挥舞一件物品。他们有时也会放下手中的武器。
> 部分怪物可以自主的装备上武器

- src/monattack.cpp
> 降低一点怪物装备武器的触发几率

- src/main_menu.cpp
- src/worldfactory.cpp
- src/worldfactory.h
> 可以在开始界面编辑世界模组

- src/main_menu.cpp
> 清理遗留在 PR #408 中的多余的代码

- src/monattack.cpp
> 添加一个检测来判断怪物能不能拿起物品 + 修改一下怪物拿起物品时输出的信息

- data/json/furniture_and_terrain/appliances.json
- src/monattack.cpp
- src/vehicle.cpp
> 修复asrg双倍发电 + 修复怪物放下物品的坐标

- data/raw/keybindings.json
- src/magic.cpp
> DDA端-来自dseguin：如果法术信息太长，显示滚动条

- android/gradle.properties
> 将安卓api等级提升到33

- src/map.cpp
> DDA端-来自inogenous：避免生成怪物时的无线循环

- src/lightmap.cpp
- src/map.cpp
- src/map.h
- src/mapbuffer.cpp
- src/mapgen.cpp
- src/savegame.cpp
- src/savegame_json.cpp
- src/submap.cpp
- src/submap.h
- src/timed_event.cpp
- src/timed_event.h
> DDA端-来自andrei8l：通过仅在需要时分配submap数据来优化内存使用。

- .gitignore
- Makefile
- android/app/build.gradle
- android/gradle.properties
- src/map.cpp
- src/third-party/parallel_hashmap/btree.h
- src/third-party/parallel_hashmap/meminfo.h
- src/third-party/parallel_hashmap/phmap.h
- src/third-party/parallel_hashmap/phmap_base.h
- src/third-party/parallel_hashmap/phmap_bits.h
- src/third-party/parallel_hashmap/phmap_config.h
- src/third-party/parallel_hashmap/phmap_dump.h
- src/third-party/parallel_hashmap/phmap_fwd_decl.h
- src/third-party/parallel_hashmap/phmap_utils.h
- src/version.cpp
- src/version.h
None
在此场景下，等待1小时，相比之前，大约减少了7.5%的性能损耗
除此之外，还引入了一个第三方库。
> 对于单纯的电器，跳过gain_moves()

- src/debug.cpp
- src/options.cpp
> 添加选项，可以不再弹出错误信息

- data/core/game_balance.json
- data/json/furniture_and_terrain/terrain-liquids.json
- data/json/mapgen/ocean.json
- data/json/overmap/overmap_terrain/overmap_terrain_waterbody.json
- data/json/overmap/special_locations.json
- data/json/regional_map_settings.json
- data/mods/Backrooms/regional_map_settings.json
- data/mods/No_Hope/regional_map_settings.json
- data/mods/TropiCataclysm/tropical_regional_map_settings.json
- data/mods/aftershock_exoplanet/region_settings.json
- data/mods/classic_zombies/alberta_regional_map_settings.json
- data/mods/desert_region/desert_regional_map_settings.json
- data/mods/rural_biome/rural_regional_map_settings.json
- src/game.cpp
- src/iuse.cpp
- src/mapgen_functions.cpp
- src/mapgen_functions.h
- src/omdata.h
- src/overmap.cpp
- src/overmap.h
- src/overmap_noise.cpp
- src/overmap_noise.h
- src/overmap_ui.cpp
- src/regional_settings.cpp
- src/regional_settings.h
- src/savegame.cpp
> DDA端-来自I-am-Erk：更有倾向性的生成大地图，以模拟地理 +  添加海洋

- data/credits/en.credits
- data/credits/zh_CN.credits
- src/overmap.cpp
- src/overmap.h
> 更新特别感谢名单 + DDA端-来自gkarfakis19：修复湖泊中的怪物生成在海里的问题

- src/vehicle.cpp
加快 traverse_vehicle_graph()
加快当周围存在大量电器/载具时的游戏速度。
1 当有大量电器/载具的场景下，遍历载具图的过程中，查找`visited_vehs` 和 `visited_targets`这两个vector中特定的元素变的很慢，多次查找变得更慢。性能瓶颈在于查找的操作。
2  对于`visited_vehs`和`visited_targets`，插入其中的元素顺序并不是需要关注的，同时并不需要应用复杂的查询条件，仅仅是判断`current_veh->parts[p].target.second`、`target_veh`是不是在相应的容器中，因此应使用在查找上更加友好的无序set容器，并使用无序set的find函数。但是我们之前引入了更加高效的第三方库，我们使用`flat_hash_set`。
在下面这个场景，等待一下时，前后分别测试三次。此次改动大约减少了traverse_vehicle_graph() **%10** 的性能损耗。
**之前**
**1**
**2**
**3**
**之后**
**1**
**2**
**3**
> 加快当周围存在大量电器/载具时的游戏速度。

- src/vehicle.cpp
> Revert "错误的PR"

- android/app/src/main/java/org/libsdl/app/SDLActivity.java
> 安卓端：修复强制全屏不起作用的问题

- android/app/src/main/java/org/libsdl/app/SDLActivity.java
Reverts WhiteCloud0123/CDDA-Breeze#468
> Revert "安卓端：修复强制全屏不起作用的问题"

- src/vehicle.cpp
None
继续加快traverse_vehicle_graph()
优先检查visited_targets有没有目标元素，以最终实现加快traverse_vehicle_graph()
> 继续加快traverse_vehicle_graph()

- data/raw/keybindings.json
- src/magic.cpp
- src/magic.h
- src/ui.cpp
- src/ui.h
> DDA端-来自lispcoc：在施法界面，根据法术体系对法术进行分类，以及可以收藏法术。

- src/veh_appliance.cpp
- src/vehicle.cpp
- src/vehicle.h
> 略微提升一点周围存在大量电器时的速度

- data/credits/en.credits
- data/credits/zh_CN.credits
> 更新 zh_CN.credits和en.credits

- src/options.cpp
> 新版区域显示默认为开

- android/app/src/main/java/org/libsdl/app/HIDDeviceBLESteamController.java
- android/app/src/main/java/org/libsdl/app/HIDDeviceManager.java
- android/app/src/main/java/org/libsdl/app/HIDDeviceUSB.java
- android/app/src/main/java/org/libsdl/app/SDL.java
- android/app/src/main/java/org/libsdl/app/SDLActivity.java
- android/app/src/main/java/org/libsdl/app/SDLAudioManager.java
- android/app/src/main/java/org/libsdl/app/SDLControllerManager.java
- android/app/src/main/java/org/libsdl/app/SDLSurface.java
Reverts WhiteCloud0123/CDDA-Breeze#470
> Revert "Revert "更新安卓端依赖的SDL库至2.28.5、更新其对应的java文件""

- src/options.cpp
> 将默认贴图更改为MSXotto+

- src/iuse.cpp
> 扫描书籍的时候，如果书籍不是自己的，并且物主看到了你，添加一个警告。

- src/iuse.cpp
> 撤销 与"扫描书籍的时候，如果书籍不是自己的，并且物主看到了你，添加一个警告。"相关的更改

- src/vehicle.cpp
> 修复安卓端的npc不会使用载具武器的问题

- src/sdltiles.cpp
> android分支 :Update sdltiles.cpp

- src/do_turn.cpp
- src/handle_action.cpp
- src/savegame.cpp
- src/sdltiles.cpp
> 使用更加高效的容器维护安卓端的快捷键映射

- src/do_turn.cpp
- src/handle_action.cpp
- src/savegame.cpp
- src/sdltiles.cpp
This reverts commit 946de1e2bf6e5a0c41a1bd0a2b2fc0098ed3667a.
None
> Revert "使用更加高效的容器维护安卓端的快捷键映射"

- src/game.cpp
- src/inventory.cpp
- src/options.cpp
- src/sdltiles.cpp
> 安卓端：将“自动添加物品菜单选项至快捷键”从设置中移除，它目前是一个完全过时且没有意义的选项，开启它还会在物品栏界面将部分快捷键从画面上移除。

- src/activity_item_handling.cpp
> 使npc可以拆解载具上的物品

- src/npcmove.cpp
> DDA端-来自I-am-Erk：修复npc不会装填它们物品栏中的弹匣的问题

- src/item.cpp
- src/item.h
- src/item_search.cpp
- src/itype.cpp
- src/itype.h
- src/iuse.cpp
- src/recipe_dictionary.cpp
- src/string_id.h
> DDA端-来自Brambor：修复高级物品管理无法按特性搜索物品的问题

- src/vehicle_autodrive.cpp
> DDA端-来自inogenous：允许自动驾驶通过桥梁

- src/character.cpp
- src/game.cpp
- src/game_constants.h
- src/lightmap.cpp
- src/lightmap.h
- src/shadowcasting.cpp
> To reality_bubble_test分支：增加现实气泡的大小。玩家视野半径提到到84，射程最大范围提高到84。

- src/character.cpp
- src/game.cpp
- src/game_constants.h
- src/lightmap.cpp
- src/lightmap.h
- src/shadowcasting.cpp
> 增大现实气泡的范围，视野与远程攻击的最大范围提高到72.

- src/mutation.cpp
> 对于Character::has_trait，使用find而不是count

- src/do_turn.cpp
- src/handle_action.cpp
- src/savegame.cpp
- src/sdltiles.cpp
> 使用更高效的容器维护安卓快捷键映射

- src/flood_fill.h
- src/mapgen_functions.cpp
- src/overmap.cpp
- src/vehicle_autodrive.cpp
> 容器替换-ff::point_flood_fill_4_connected

- src/vehicle_autodrive.cpp
> DDA端-来自inogenous：修复自动驾驶时车辆速度瞬间突增的问题

- src/character.cpp
- src/third-party/veque/veque.hpp
> 加快Character::leak_items

- src/character.cpp
> 加快Character::process_items()

- src/cata_tiles.cpp
> 加快cata_tiles::draw

- android/app/build.gradle
- android/app/src/main/java/org/libsdl/app/SDLActivity.java
- android/build.gradle
> 安卓消息推送换用Toaster框架

- android/app/build.gradle
- android/app/src/main/java/org/libsdl/app/SDLActivity.java
- android/build.gradle
This reverts commit 265d73cd0f75d6e7bb48640509f446c1dc6cb1f7.
None
> Revert "安卓消息推送换用Toaster框架"

- src/monster.cpp
> 如果怪物处在载具上，怪物的产物，例如粪便和蛋，优先放置到载具上

- android/app/build.gradle
- android/app/src/main/java/org/libsdl/app/SDLActivity.java
- android/build.gradle
- android/gradle.properties
> 添加Jitpack源/启用AndroidX

- android/app/build.gradle
- android/app/src/main/java/org/libsdl/app/SDLActivity.java
> 消息推送换用Toaster框架

- src/sdltiles.cpp
> handle_finger_input :避免多次计算delta_y的绝对值

- android/app/build.gradle
- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/com/cleverraven/cataclysmdda/SplashScreen.java
- android/app/src/main/java/org/libsdl/app/SDLActivity.java
- android/build.gradle
- src/main.cpp
> develop -> p_r_e     安卓端：将数据的读写移动到公共存储区域

- android/build.gradle
> gradle版本指定为7.3.0

- android/app/src/main/java/org/libsdl/app/SDLActivity.java
> Toaster顶部显示消息

- src/flexbuffer_cache.cpp
> DDA端-来自akrieger：Fix flexbuffer cache post-c++-17 migration

- android/app/build.gradle
> 安卓端：-Ofast

- android/app/build.gradle
Reverts WhiteCloud0123/CDDA-Breeze#600
> Revert "安卓端：-Ofast"

- src/cata_tiles.cpp
- src/cata_tiles.h
> 换另一种方式绘制生物血条

- src/game.cpp
- src/game.h
- src/overmap_ui.cpp
This reverts commit 2031f33e3c86f4288a9c8f7f55c7bea4bbdd99fd.
> Revert "安卓端：修复大地图界面无法接收多指输入的问题"

- src/map.cpp
- src/map.h
- src/npc_attack.cpp
- src/npcmove.cpp
> 让npc能够在可透视的掩体后射击

- src/character.cpp
- src/creature.cpp
- src/melee.cpp
> 战斗气泡动画：用实际数字表示给与/受到的伤害

- data/json/player_activities.json
> 为挖掘区进行的行动和屠宰菜单上的各种行动添加上“auto_needs“

- src/player_activity.cpp
> 快速修复区域清空活动无法连续结合拆卸枪械模组活动的问题

- src/character_guns.cpp
> 修复区域清空活动不能连续移除枪械模组的问题

- src/activity_actor.cpp
> 结合几个函数的功能，用一个新的静态函数更好的解决区域清空活动无法连续移除枪械模组的问题，为了一致性，将移除的模组同样放在地上。

- src/activity_actor.cpp
- src/game.cpp
- src/iuse_actor.cpp
- src/mattack_actors.cpp
> 让一些放置的怪物类型的炮塔使用子弹带

- src/lightmap.cpp
> DDA端-来自Surflurer：修复apply_light_arc的精度问题

- src/iuse_actor.cpp
> 修复place_monster_iuse::use中的迭代器更新
